version: '3.8'

services:
  biocode:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"
      - "9090:9090"
    environment:
      - BIOCODE_ENVIRONMENT=development
    volumes:
      - ../../src:/app/src
      - ../../tests:/app/tests
      - biocode_data:/app/data
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      
  prometheus:
    image: prom/prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

volumes:
  biocode_data:
  redis_data:
  prometheus_data:
